name: zeal-casept # you probably want to 'snapcraft register <name>'
version: '0.3.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Zeal is a simple offline documentation browser inspired by Dash.
description: |
        Zeal is a simple offline documentation browser inspired by Dash. This is an unofficial build.

grade: stable 
confinement: strict
apps:
  zeal:
    command: qt5-launch usr/bin/zeal
    plugs: [network, x11, browser-support]
parts:
  qt:
    plugin: nil
    stage-packages:
      - libqt5concurrent5
      - libqt5core5a
      - libqt5dbus5
      - libqt5gui5
      - libqt5network5
      - libqt5svg5
      - libqt5widgets5
      - libqt5x11extras5
      - libqt5xml5
      - libqt5webkit5
      - libqt5sql5-sqlite

  zeal:
    plugin: qmake
    qt-version: qt5
    source: https://github.com/zealdocs/zeal/archive/v0.3.1.tar.gz
    build-packages:
      - build-essential
      - libarchive-dev
      - libappindicator-dev
      - libxcb-keysyms1-dev
      - zlib1g-dev
      - libx11-dev
      - libxslt1-dev
      - libqt5x11extras5-dev
      - libqt5webkit5-dev
#      - libqt5webenginewidgets5
    stage-packages:
      - xcb
      - libxcb-cursor0
    after: [qt]

  launcher:
    plugin: copy
    files:
      qt5-launch: bin/qt5-launch

  integration:
    plugin: nil
    stage-packages:
      - ttf-ubuntu-font-family
    snap:
      - usr/share
      - -usr/share/doc
