name: zeal-casept # you probably want to 'snapcraft register <name>'
version: '0.4.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: Zeal is a simple offline documentation browser inspired by Dash.
description: |
        Zeal is a simple offline documentation browser inspired by Dash. This is an unofficial build.

grade: stable 
confinement: strict
apps:
  zeal:
    command: desktop-launch $SNAP/usr/bin/zeal
    plugs: [network, x11, unity7, browser-support]
parts:

  zeal:
    plugin: qmake
    qt-version: "qt5"
    source: https://github.com/zealdocs/zeal/archive/v0.4.0.tar.gz
    build-packages:
      - build-essential
      - libarchive-dev
      - libappindicator-dev
      - libxcb-keysyms1-dev
      - zlib1g-dev
      - libx11-dev
      - libxslt1-dev
      - libqt5x11extras5-dev
      - libqt5webkit5-dev
    stage-packages:
      - xcb
      - libarchive13
      - libxcb-cursor0
      - libqt5sql5-sqlite
    after: [desktop-qt5]
